services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nasa-koi-backend
    ports:
      - "8001:8001"
    environment:
      - HOST=0.0.0.0
      - PORT=8001
      - DEBUG=False
      - UPLOAD_DIR=/app/uploads
      - MODEL_DIR=/app/models
      - LOG_LEVEL=INFO
      - PYTHONPATH=/app
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/models:/app/models
      - ./backend/logs:/app/logs
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8001/ping', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  uploads:
  models:
  logs: