services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: nasa-koi-backend
    ports:
      - "8001:8001"
    environment:
      - HOST=0.0.0.0
      - PORT=8001
      - UPLOAD_DIR=/app/uploads
      - MODEL_PATH=/app/models
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/models:/app/models
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - nasa-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: nasa-koi-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:8001
      - NEXT_PUBLIC_APP_NAME=NASA KOI Portal
      - NEXT_PUBLIC_APP_VERSION=1.0.0
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks:
      - nasa-network

  nginx:
    image: nginx:alpine
    container_name: nasa-koi-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - nasa-network

networks:
  nasa-network:
    driver: bridge

volumes:
  uploads:
  models: